### ISSUE TITLE
WIFI连接为什么用不了

### ISSUE THREAD

**Issue by sggc** [pdone/FreeControl#10]
有什么注意事项或是详细的操作过程吗

**Comment by liiloo100** [comment]
我这样做就可以了
先连接数据线，再运行下面的命令，无线连接就正常了
adb tcpip 5555

**Comment by pdone** [comment]
首次使用需要先连接数据线，执行adb tcpip 5555，然后拔掉数据线，输入ip和端口号5555，勾选无线访问，点启动。
或者启用高版本安卓系统的无线调试，默认端口号一般不是5555。
