### ISSUE TITLE
[Bug] 启动后2秒显示已退出

### ISSUE THREAD

**Issue by acutecat** [pdone/FreeControl#118]
1. 点击启动后，2秒显示已退出，下面是日志
2. 尝试在不同电脑和手机都会有该提示

[2024-11-28.log](https://github.com/user-attachments/files/17944383/2024-11-28.log)

**Comment by pdone** [comment]
打开配置文件，尝试把  `"CustomArgs":"--keyboard=uhid"` 改为 `"CustomArgs":""`，看日志显示权限不足，把这个参数去掉试试吧

**Comment by acutecat** [comment]
好的，已解决，谢谢
