### ISSUE TITLE
我使用中遇到的问题

### ISSUE THREAD

**Issue by saresam** [pdone/FreeControl#2]
部分快捷键，不灵敏时好时坏，反应有点慢。
无线访问用不了，闪过显示已退出。

不知道这些问题是我电脑的问题还是我手机的问题呢？还是我操作的问题？

**Comment by saresam** [comment]
Loading device list
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Setting port
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Faild
Press any key to exit

**Comment by pierrecashon** [comment]
连上了,但是电脑没办法操控手机,,显示和设置啥的都是正常的

**Comment by pdone** [comment]
> 连上了,但是电脑没办法操控手机,,显示和设置啥的都是正常的

v1.3.1版本已解决此问题
提供一个临时解决方案：先关闭程序，然后 删除 %Appdata%/Free Control/config.json，重新打开程序

**Comment by 15909509587** [comment]
Loading device list
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Setting port
'adb' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Faild
Press any key to exit
您好，以前是一切正常的，更新win11之后出现这种情况，重新下载也不行，数据线能正常，WiFi端口设置不了
谢谢

**Comment by pdone** [comment]
我又回来了，请下载1.6.1版本，如果还有以上问题，请留言反馈。
