### ISSUE TITLE
红米10+WIN7，无法启动free control

### ISSUE THREAD

**Issue by friedrica137** [pdone/FreeControl#23]
有线连接：确认手机usb调试已打开，手机连接电脑后“仅充电”、“传输文件”、“传输照片”3种模式均分别尝试，点击“启动”后，显示正在启动，20秒后提示“已退出”。
无线连接：确认ip地址无误。点击“启动”后，马上提示“已退出”；设置端口号时报错，
error: no devices/emulators found
Falid

重装电脑前free control一切正常的呜呜呜呜呜

**Comment by pdone** [comment]
请尝试最新版v1.6.2。
