### ISSUE TITLE
下载好源码后如何编译运行，需要什么环境，可以放到readme里介绍一下嘛

### ISSUE THREAD

**Issue by yutianch** [pdone/FreeControl#26]

**Comment by pdone** [comment]
抱歉最近太忙没有精力维护，目前该项目依赖.NET Framework 4.7.2，本机安装此版本的SDK即可。[https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/net472](https://dotnet.microsoft.com/zh-cn/download/dotnet-framework/net472)
