### ISSUE TITLE
怎么直接使用adb.exe 并且不用绝对路径，不加环境变量，adb.exe 怎么直接集合到程序的exe中运行？

### ISSUE THREAD

**Issue by Stephen-S0** [pdone/FreeControl#27]
怎么直接使用adb.exe 并且不用绝对路径，不加环境变量，adb.exe 怎么直接集合到程序的exe中运行？

**Comment by pdone** [comment]
`SunnyUI.dll` 我就是把他设置成内嵌的资源，程序启动时加载依赖的。
没有试过exe作为内嵌资源，程序内部还能不能调用。可以尝试一下使用内嵌资源方式去实现。
