### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by rp1231** [pdone/FreeControl#29]
I'm getting this message when I try to start FreeControl:
<img width="200" alt="FreeControl_RvimxItZYl" src="https://github.com/pdone/FreeControl/assets/47380919/917a0f5a-3661-4b79-a86a-db8d3243c186">

**Comment by pdone** [comment]
Description:
Version 1.6.1 adds updates. When using the new version, delete the scrcpy resources of the old version, forget to judge whether it exists before deleting, resulting in failure of deletion. It is a very careless bug. I am very sorry!
Please use version 1.6.2, judgment has been added.
