### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by kkzdq** [pdone/FreeControl#33]
win10 最新1.6.1启动失败 管理员身份启动也不行

**Comment by SevenLoveme** [comment]
一样的问题附log
2023-08-25 10:11:55:662 [ERROR] System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\31056\AppData\Roaming\FreeControl\scrcpy-win64-v2.1.1\”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   在 FreeControl.Main.ExtractResource(Boolean reload)
   在 FreeControl.Main.InitPdone()
   在 FreeControl.Main..ctor()
   在 FreeControl.Trusteeship..ctor()
   在 FreeControl.Program.Main()
2023-08-25 10:12:25:359 [ERROR] System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\31056\AppData\Roaming\FreeControl\scrcpy-win64-v2.1.1\”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   在 FreeControl.Main.ExtractResource(Boolean reload)
   在 FreeControl.Main.InitPdone()
   在 FreeControl.Main..ctor()
   在 FreeControl.Trusteeship..ctor()
   在 FreeControl.Program.Main()

**Comment by pdone** [comment]
电脑是否安装了 `.NET Framework 4.7.2`，如果安装了依然存在这个问题，请留下联系方式。

**Comment by pdone** [comment]
情况说明：
1.6.1版本增加了更新使用新版本时，删除旧版本的scrcpy资源，删除前忘记判断是否存在了，导致删除失败了，属于非常粗心的bug了，非常抱歉！
请使用1.6.2版本，已增加判断。
