### ISSUE TITLE
涉及解锁、加密视频播放屏幕黑屏

### ISSUE THREAD

**Issue by fang-mao** [pdone/FreeControl#43]
1. 微信有手势锁和指纹锁，打开微信黑屏
2. 对于加密视频播放软件如大黄蜂视频，打开软件后后黑屏无法显示

**Comment by pdone** [comment]
在涉及安全性较高的操作时，电脑上会显示黑屏，这是安卓12+的安全机制。通过root和xposed模块，禁用 `FLAG_SECURE` 也许可以解决这个问题。

可参考以下内容，希望对你有所帮助：
[https://github.com/Genymobile/scrcpy/issues/2129](https://github.com/Genymobile/scrcpy/issues/2129)
[https://github.com/Genymobile/scrcpy/issues/3899](https://github.com/Genymobile/scrcpy/issues/3899)

**Comment by renoce** [comment]
为什么scrcpy v1.25没这个问题？

**Comment by renoce** [comment]
@pdone
