### ISSUE TITLE
意外断开连接时恢复输入法

### ISSUE THREAD

**Issue by yihao0628** [pdone/FreeControl#65]
正常退出的时候输入法会恢复为启动之前的输入法，但是如果因为无线断开退出的连接时，输入法无法自动切回，希望可以在网络断掉时可以恢复输入法，我不知道这个如何实现，但是在晨钟酱的scrcpy中 “断开锁屏功能”应该使用到了类似的实现方式，无论以何种方式断开连接，手机都将立即锁屏，希望可以优化该项功能，目前没有找到比freecontrol使用起来更舒服的同类工具

**Comment by yihao0628** [comment]
催更催更，scrspy官方项目出2.4了，跟进一下大佬

**Comment by pdone** [comment]
无线连接的时候，如果是正常退出的话，我测试是可以恢复输入法的。

但如果是在手机端直接把网络断掉，就无法恢复了。（有线连接直接拔掉数据线，也是同样的情况）

本程序实现恢复输入法的方式是通过adb命令，如果adb连接断开，便无法恢复了。

**Comment by yihao0628** [comment]
> 无线连接的时候，如果是正常退出的话，我测试是可以恢复输入法的。
> 
> 但如果是在手机端直接把网络断掉，就无法恢复了。（有线连接直接拔掉数据线，也是同样的情况）
> 
> 本程序实现恢复输入法的方式是通过adb命令，如果adb连接断开，便无法恢复了。

我的猜想是能不能在连接过程中就给手机里运行一个定时脚本检测adb连接状态，意外断开时触发恢复输入法，这样即使意外断开adb，已经无法发送shell命令也可以切换输入法

**Comment by pdone** [comment]
> > 无线连接的时候，如果是正常退出的话，我测试是可以恢复输入法的。
> > 但如果是在手机端直接把网络断掉，就无法恢复了。（有线连接直接拔掉数据线，也是同样的情况）
> > 本程序实现恢复输入法的方式是通过adb命令，如果adb连接断开，便无法恢复了。
> 
> 我的猜想是能不能在连接过程中就给手机里运行一个定时脚本检测adb连接状态，意外断开时触发恢复输入法，这样即使意外断开adb，已经无法发送shell命令也可以切换输入法

是的，如果真想实现的话，就是你猜想的那样，在手机端监控来实现。好消息是，我测试scrcpy 2.4下，之前无法拼音输入的输入法，已经可以正常输入，本程序的切换输入法功能可以下线了。

**Comment by pdone** [comment]
通过scrcpy 2.4的最新特性 `UHID keyboard` 即可实现模拟物理键盘输入。

**Comment by yihao0628** [comment]
> > > 无线连接的时候，如果是正常退出的话，我测试是可以恢复输入法的。
> > > 但如果是在手机端直接把网络断掉，就无法恢复了。（有线连接直接拔掉数据线，也是同样的情况）
> > > 本程序实现恢复输入法的方式是通过adb命令，如果adb连接断开，便无法恢复了。
> > 
> > 
> > 我的猜想是能不能在连接过程中就给手机里运行一个定时脚本检测adb连接状态，意外断开时触发恢复输入法，这样即使意外断开adb，已经无法发送shell命令也可以切换输入法
> 
> 是的，如果真想实现的话，就是你猜想的那样，在手机端监控来实现。好消息是，我测试scrcpy 2.4下，之前无法拼音输入的输入法，已经可以正常输入，本程序的切换输入法功能可以下线了。

难道这样可以顺利让所有输入法都输入中文吗？

**Comment by pdone** [comment]
可以理解为，把电脑键盘，模拟为直接连接到手机的物理键盘，而大部分输入法对物理键盘都有支持。
请等待FreeControl1.7.0版本更新。或者使用原生scrcpy2.4提前尝试。

**Comment by yihao0628** [comment]
太好了，回头我就尝试scecpy2.4能否正常使用搜狗拼音输入法MIUI专版输入，我曾自己替换FreeControl数据目录下的scecpy，然后无法启动FreeControl了，哈哈

**Comment by pdone** [comment]
> 太好了，回头我就尝试scecpy2.4能否正常使用搜狗拼音输入法MIUI专版输入，我曾自己替换FreeControl数据目录下的scecpy，然后无法启动FreeControl了，哈哈

已测试 搜狗输入法MIUI版 可正常输入。
![image](https://github.com/pdone/FreeControl/assets/34151215/21c2367a-5170-4103-9620-e217934eb2d0)

**Comment by pdone** [comment]
`v1.7.0` 已发布
