### ISSUE TITLE
加入个按键映射？或者鼠标点击？

### ISSUE THREAD

**Issue by TAOsame** [pdone/FreeControl#7]
参考模拟器设置按键
按键对应一些位置的点击
![微信图片_20210722162008](https://user-images.githubusercontent.com/43315189/126609445-14552637-be85-4e34-80c4-0cb6f738741f.png)

**Comment by pdone** [comment]
[https://github.com/barry-ran/QtScrcpy](https://github.com/barry-ran/QtScrcpy)
已经有更好用的啦 请尝试QtScrcpy
